# Generated by Django 4.1.4 on 2022-12-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressoras',
            fields=[
                ('ident', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=12)),
                ('serial', models.CharField(max_length=20)),
                ('setor', models.CharField(max_length=10)),
            ],
        ),
    ]
