# Generated by Django 4.1.4 on 2022-12-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scga', '0002_impressoras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impressoras',
            old_name='serial',
            new_name='cupsid',
        ),
    ]
